openapi: "3.0.3"

info:
  version: "3.0"
  title: Hello World
  description: |
    # Overview
    Testing various endpoint combinations in the AWS API Gateway
servers:
- url: https://test-api.service.hmrc.gov.uk/hello
  description: Sandbox
- url: https://api.service.hmrc.gov.uk/hello
  description: Production

components:
  parameters:
    acceptHeader:
      name: Accept
      in: header
      schema:
        type: string
        enum: [ "application/vnd.hmrc.3.0+json" ]
      required: true
    yearPath:
      name: year
      in: path
      description: |
        The year
      schema:
        type: string
        example: 2021
      required: true
    yearQuery:
      name: year
      in: query
      description: |
        The year
      schema:
        type: string
        example: 2021
      required: true

paths:
  /world/{year}:
    get:
      summary: Hello world with a year in path and query
      parameters:
      - $ref: '#/components/parameters/acceptHeader'
      - $ref: '#/components/parameters/yearPath'
      - $ref: '#/components/parameters/yearQuery'
      responses:
        201:
          description: "No Content"
      security:
      - {}


