openapi: "3.0.3"

info:
  version: "3.0"
  title: Hello World
  description: |
    # Overview
    Testing various endpoint combinations in the AWS API Gateway
servers:
- url: https://test-api.service.hmrc.gov.uk
  description: Sandbox
- url: https://api.service.hmrc.gov.uk/
  description: Production

components:
  parameters:
    acceptHeader:
      name: Accept
      in: header
      schema:
        type: string
        enum: [ "application/vnd.hmrc.3.0+json" ]
      required: true
    year:
      name: Year
      in: path
      description: |
        The year
      schema:
        type: string
        example: 2021
      required: true
    name:
      name: Name
      in: path
      description: |
        The name
      schema:
        type: string
        example: Alice
      required: true

paths:
  /hello/world/{year}/{name}:
    get:
      summary: Hello world with a year
      parameters:
      - $ref: '#/components/parameters/acceptHeader'
      - $ref: '#/components/parameters/year'
      - $ref: '#/components/parameters/name'
      responses:
        201:
          description: "No Content"
      security:
      - {}
      
  /hello/world/peace/{year}:
    get:
      summary: Hello with a name and year
      parameters:
      - $ref: '#/components/parameters/acceptHeader'
      - $ref: '#/components/parameters/year'
      responses:
        201:
          description: "No Content"
      security:
      - {}

